In [1]:
#pip install torch torchvision

### Compare with Numpy 

In [2]:
import torch
import numpy as np

### Quick ref At:

https://pytorch.org/docs/stable/torch.html

### Data type 

![caption](dataType.png)

### Gpu tensor e.g:   torch.cuda.FloatTensor

### Default torch is float and default numpy is double

### Initialize

In [7]:
# Initialize Directly
t1 = torch.tensor([1,2,3,4]) # from python list
t2 = torch.tensor(np.array([1,2,3,4])) # from numpy array
print(f'Initialize Directly:\n{t1}\n{t2}\n')

#Check Type of a data structure
print(f'\nType of arr1: {type(t1)}\n')

#Initialize nparray with data type
print(f'Initialize nparray with data type: {torch.tensor([1,2,3],dtype=torch.float)}') 

#Initialize nparray as float
print(f'Initialize nparray with Same type: {torch.tensor([1.,2,3])}') 

Initialize Directly:
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4], dtype=torch.int32)


Type of arr1: <class 'torch.Tensor'>

Initialize nparray with data type: tensor([1., 2., 3.])
Initialize nparray with Same type: tensor([1., 2., 3.])


### Generate

In [11]:
# Initialize a zeros nparray 
print(f'Initialize Zeros: \n{torch.zeros((2,3))}\n') # Note the argument is shape so double brackets

# Initialize a Ones nparray 
print(f'Initialize Ones: \n{torch.ones((2,3),dtype=torch.float)}\n') # Note the argument is shape so double brackets

# Random int with range 2-10 and size (2,3)
print(f'Random int with range 2-10 and size (2,3):\n {torch.randint(2,10,size=(2,3))}\n') 

# Initialize the Identity Matrix
print(f'Initialize Identity Matrix: \n{torch.eye(3,3)}\n')

# Standard Normally distributed N(0,1) numbers of size (2,4,5)
print(f' Standard Normally distributed N(0,1) numbers of size (2,4,5):\n {torch.rand(2,4,5)}')

Initialize Zeros: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Initialize Ones: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random int with range 2-10 and size (2,3):
 tensor([[2, 5, 7],
        [6, 7, 9]])

Initialize Identity Matrix: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

 Standard Normally distributed N(0,1) numbers of size (2,4,5):
 tensor([[[0.4895, 0.5677, 0.4622, 0.6719, 0.2694],
         [0.5358, 0.6087, 0.2552, 0.3818, 0.9457],
         [0.1450, 0.4669, 0.2059, 0.3943, 0.1973],
         [0.8918, 0.1149, 0.3374, 0.0012, 0.2494]],

        [[0.4323, 0.3398, 0.3363, 0.7495, 0.8430],
         [0.9092, 0.4651, 0.1207, 0.4188, 0.9716],
         [0.1617, 0.2279, 0.1208, 0.3436, 0.3333],
         [0.1010, 0.7890, 0.3359, 0.0663, 0.2908]]])


In [14]:
# Arrange a numpy array
print(f'Arrange: {torch.arange(3,10)}')

#  evenly spaced numbers over a specified interval
print(f'LineSpace: {torch.linspace(2.0, 3.0, steps=5)}')

Arrange: tensor([3, 4, 5, 6, 7, 8, 9])
LineSpace: tensor([2.0000, 2.2500, 2.5000, 2.7500, 3.0000])


### Torch to Nparray and viceversa 

In [10]:
print('Numpy to Tensor\n','=='*7)
npArr = np.array([1,2,3])
tensorArr = torch.tensor(npArr) 
print(f'npArr to Tensor: {tensorArr} ')
t3 = torch.from_numpy(npArr)
print('Numpy array to tensor: from_numpy:',t3)
#Clone
tensorArr_clone = tensorArr.clone().detach()
print(f'Clone of tensorArr: {tensorArr_clone}')

print('\nTensor to Numpy\n')
t1 = torch.tensor([1,2,3,4])
t2 = t1.detach().numpy()


print('Tensor:',t1)
print('Numpy array:',t2)




Numpy to Tensor
npArr to Tensor: tensor([1, 2, 3], dtype=torch.int32) 
Numpy array to tensor: from_numpy: tensor([1, 2, 3], dtype=torch.int32)
Clone of tensorArr: tensor([1, 2, 3], dtype=torch.int32)

Tensor to Numpy

Tensor: tensor([1, 2, 3, 4])
Numpy array: [1 2 3 4]


### Shuffling


In [24]:
t = torch.tensor([[1,2],[3,4]])
print(f'Original t{t}\n')
idx = torch.randperm(t.nelement())
t = t.view(-1)[idx].view(t.size())
print(f'Shuffled t{t}\n')

Original ttensor([[1, 2],
        [3, 4]])

Shuffled ttensor([[3, 1],
        [4, 2]])



### Reshape and View 


View vs Reshape:https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [38]:
# Reshape the nparray
arr_a = torch.arange(12)
print(f'arr_a before: {arr_a}')

arr_b = torch.reshape(arr_a,(3,4))
print(f'Reshape the dimension of nparray:\n {arr_b}\n') # Note : dimension should match
print('Shape: ',arr_b.shape)



arr_a before: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshape the dimension of nparray:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Shape:  torch.Size([3, 4])


In [7]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Get Python number for single element

In [8]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7272])
0.7272418737411499


### Transpose

In [41]:
## Transpose 

print('Original nparray:\n',arr_b,arr_b.shape,'\nTranspose: \n',arr_b.T,arr_b.T.shape)

x = torch.ones((1, 2, 3))
print(f'\nShape of Original x: {x.shape}\t \nShape of Transpose(1,0,2): {torch.transpose(x,  0, 2).shape}')

t = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])

print(t.shape)
print(t)
print('\n')

print(t.transpose(0,1).shape)
print(t.transpose(0,1))
print('\n')

print(t.transpose(0,2).shape)
print(t.transpose(0,2))
print('\n')

Original nparray:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) torch.Size([3, 4]) 
Transpose: 
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]) torch.Size([4, 3])

Shape of Original x: torch.Size([1, 2, 3])	 
Shape of Transpose(1,0,2): torch.Size([3, 2, 1])
torch.Size([2, 3, 4])
tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]])


torch.Size([3, 2, 4])
tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  9,  10,  11,  12],
         [ -9, -10, -11, -12]]])


torch.Size([4, 3, 2])
tensor([[[  1,  -1],
         [  5,  -5],
         [  9,  -9]],

        [[  2,  -2],
         [  6,  -6],
         [ 10, -10]],

        [[  3,  -3],
         [  7,  -7],
         [ 11, -11]],

        [[  4,  -4]

#### Transpose(1,2,0)   =>  H W C to C H W    
---
#### torch.transpose(npimg, (1, 2, 0)
---
#### Or torch image=>img = torch.transpose(img,2,0)

In [42]:
t = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])

print(t.shape)
print(t)
print('\n')

print(t.permute(1,0,2).shape)
print(t.permute(1,0,2))
print('\n')

print(t.permute(1,2,0).shape)
print(t.permute(1,2,0))
print('\n')

torch.Size([2, 3, 4])
tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]])


torch.Size([3, 2, 4])
tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  9,  10,  11,  12],
         [ -9, -10, -11, -12]]])


torch.Size([3, 4, 2])
tensor([[[  1,  -1],
         [  2,  -2],
         [  3,  -3],
         [  4,  -4]],

        [[  5,  -5],
         [  6,  -6],
         [  7,  -7],
         [  8,  -8]],

        [[  9,  -9],
         [ 10, -10],
         [ 11, -11],
         [ 12, -12]]])




### Flatten

In [25]:
t = torch.rand(size=(2,3,4))
print(f'Original:\n {t}\n\n Flatten:\n {t.flatten()}')

Original:
 tensor([[[0.4888, 0.9678, 0.9099, 0.1588],
         [0.7494, 0.2713, 0.0794, 0.5242],
         [0.3305, 0.9256, 0.8328, 0.4686]],

        [[0.6715, 0.2538, 0.0216, 0.4782],
         [0.5187, 0.3184, 0.1411, 0.5747],
         [0.1637, 0.9860, 0.0830, 0.6746]]])

 Flatten:
 tensor([0.4888, 0.9678, 0.9099, 0.1588, 0.7494, 0.2713, 0.0794, 0.5242, 0.3305,
        0.9256, 0.8328, 0.4686, 0.6715, 0.2538, 0.0216, 0.4782, 0.5187, 0.3184,
        0.1411, 0.5747, 0.1637, 0.9860, 0.0830, 0.6746])


### Squeeze and Unsqueeze 

In [31]:
print('\nSqueeze\n','='*10)
# squeeze removes all the 1 dimension in all axes  
t = torch.tensor([[[0], [1], [2]]])
print(f'Shape of X: {t.shape} \n Shape after Squeezed: {t.squeeze().shape}')

#Squeeze the Dimension specficed by axis
print(f'\nShape of X: {t.shape} \n Shape after Squeezed: {t.squeeze(axis=2).shape}') ## Squeezed axis 2
print('\nUnsqueeze\n','='*10)
##Unsqueeze
t1 = torch.tensor([1,2,3])
print(f'Shape of t1: {t1}\n Shape after unsqueeze axis = 1:\n{t1.unsqueeze(1).shape} ')



Squeeze
Shape of X: torch.Size([1, 3, 1]) 
 Shape after Squeezed: torch.Size([3])

Shape of X: torch.Size([1, 3, 1]) 
 Shape after Squeezed: torch.Size([1, 3])

Unsqueeze
Shape of t1: tensor([1, 2, 3])
 Shape after unsqueeze axis = 1:
torch.Size([3, 1]) 


### Permute

In [43]:
t = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])

print(t.shape)
print(t)
print('\n')

print(t.permute(1,0,2).shape)
print(t.permute(1,0,2))
print('\n')

print(t.permute(1,2,0).shape)
print(t.permute(1,2,0))
print('\n')

torch.Size([2, 3, 4])
tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]])


torch.Size([3, 2, 4])
tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  9,  10,  11,  12],
         [ -9, -10, -11, -12]]])


torch.Size([3, 4, 2])
tensor([[[  1,  -1],
         [  2,  -2],
         [  3,  -3],
         [  4,  -4]],

        [[  5,  -5],
         [  6,  -6],
         [  7,  -7],
         [  8,  -8]],

        [[  9,  -9],
         [ 10, -10],
         [ 11, -11],
         [ 12, -12]]])




### Concatenation

In [45]:
# Tensor Cat

t1 = torch.rand(size=(2,3,4))
t2 = torch.rand(size=(2,3,4))
t3 = torch.rand(size=(1,3,4))
t4 = torch.rand(size=(2,3,1))

print(t1)
print(t2)
print(t3)
print(t4)

print('Concatenating tensors\n')

print(torch.cat([t1,t2],dim=1))
print(torch.cat([t1,t2,t3],dim=0))
print(torch.cat([t1,t2,t4],dim=2))

tensor([[[0.8262, 0.7862, 0.3476, 0.8687],
         [0.0222, 0.7798, 0.3999, 0.7857],
         [0.7850, 0.8825, 0.2889, 0.0881]],

        [[0.0567, 0.5285, 0.1073, 0.2890],
         [0.1946, 0.8137, 0.4835, 0.2472],
         [0.1447, 0.1983, 0.1579, 0.6726]]])
tensor([[[0.3726, 0.0330, 0.0149, 0.7858],
         [0.5984, 0.0415, 0.7608, 0.2337],
         [0.8865, 0.0734, 0.3437, 0.6659]],

        [[0.0836, 0.0291, 0.8091, 0.8489],
         [0.0454, 0.4242, 0.7369, 0.6564],
         [0.6066, 0.8378, 0.9279, 0.2589]]])
tensor([[[0.1317, 0.0256, 0.0492, 0.1964],
         [0.4699, 0.5591, 0.4452, 0.4609],
         [0.4864, 0.5650, 0.2662, 0.8971]]])
tensor([[[0.2634],
         [0.8278],
         [0.9415]],

        [[0.0193],
         [0.3025],
         [0.0484]]])
Concatenating tensors

tensor([[[0.8262, 0.7862, 0.3476, 0.8687],
         [0.0222, 0.7798, 0.3999, 0.7857],
         [0.7850, 0.8825, 0.2889, 0.0881],
         [0.3726, 0.0330, 0.0149, 0.7858],
         [0.5984, 0.0415, 0.7608

In [46]:
# Tensor Stack
# This operation can be imagined as a combination of unsqueeze and cat.

t1 = torch.rand(size=(3,4))
t2 = torch.rand(size=(3,4))

print(t1.shape)
print(t1)
print('\n')

print(t2.shape)
print(t2)
print('\n')

print(torch.stack([t1,t2],dim=0).shape)
print(torch.stack([t1,t2],dim=0))

print(torch.stack([t1,t2],dim=1).shape)
print(torch.stack([t1,t2],dim=1))

print(torch.stack([t1,t2],dim=2).shape)
print(torch.stack([t1,t2],dim=2))

torch.Size([3, 4])
tensor([[0.1758, 0.3565, 0.2123, 0.8205],
        [0.1231, 0.0766, 0.8280, 0.8037],
        [0.1186, 0.7584, 0.6012, 0.7442]])


torch.Size([3, 4])
tensor([[0.0858, 0.3282, 0.4925, 0.3911],
        [0.7394, 0.3090, 0.5269, 0.8588],
        [0.3025, 0.8231, 0.6296, 0.0477]])


torch.Size([2, 3, 4])
tensor([[[0.1758, 0.3565, 0.2123, 0.8205],
         [0.1231, 0.0766, 0.8280, 0.8037],
         [0.1186, 0.7584, 0.6012, 0.7442]],

        [[0.0858, 0.3282, 0.4925, 0.3911],
         [0.7394, 0.3090, 0.5269, 0.8588],
         [0.3025, 0.8231, 0.6296, 0.0477]]])
torch.Size([3, 2, 4])
tensor([[[0.1758, 0.3565, 0.2123, 0.8205],
         [0.0858, 0.3282, 0.4925, 0.3911]],

        [[0.1231, 0.0766, 0.8280, 0.8037],
         [0.7394, 0.3090, 0.5269, 0.8588]],

        [[0.1186, 0.7584, 0.6012, 0.7442],
         [0.3025, 0.8231, 0.6296, 0.0477]]])
torch.Size([3, 4, 2])
tensor([[[0.1758, 0.0858],
         [0.3565, 0.3282],
         [0.2123, 0.4925],
         [0.8205, 0.3911]],

  

### Repeat

In [47]:
# Tensor Repeat

t1 = torch.rand(3)

print('Original t1:')
print(t1)

print('t1.repeat(2)')
print(t1.repeat((2)))

print('t1.repeat(4,2)')
print(t1.repeat((4,2)))

print('t1.repeat(4,2,2)')
print(t1.repeat((4,2,2)))

Original t1:
tensor([0.9795, 0.6203, 0.0287])
t1.repeat(2)
tensor([0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287])
t1.repeat(4,2)
tensor([[0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287],
        [0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287],
        [0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287],
        [0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287]])
t1.repeat(4,2,2)
tensor([[[0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287],
         [0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287]],

        [[0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287],
         [0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287]],

        [[0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287],
         [0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287]],

        [[0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287],
         [0.9795, 0.6203, 0.0287, 0.9795, 0.6203, 0.0287]]])


In [48]:
# Tensor Repeat Interleave


t1 = torch.rand(3)
t2 = torch.rand(size=(3,2))

print('Original t1:')
print(t1)

print('Original t2:')
print(t2)

print('t1.repeat_interleave(2)')
print(t1.repeat_interleave(2))

# Unless dimension is specified the multi-dimension tensor is flattened and then interleave operation is applied
print('t2.repeat_interleave(2)')
print(t2.repeat_interleave(2))

print('t2.repeat_interleave(2,dim=0)')
print(t2.repeat_interleave(2,dim=0))

print('t2.repeat_interleave(2,dim=1)')
print(t2.repeat_interleave(2,dim=1))

# Repeat interleave applied with differnet repetitions
print('t2.repeat_interleave(torch.tensor([1,2,3]),dim=0)')
print(t2.repeat_interleave(torch.tensor([1,2,3]),dim=0))

Original t1:
tensor([0.5361, 0.7571, 0.4459])
Original t2:
tensor([[0.2258, 0.2024],
        [0.7398, 0.3576],
        [0.3801, 0.3540]])
t1.repeat_interleave(2)
tensor([0.5361, 0.5361, 0.7571, 0.7571, 0.4459, 0.4459])
t2.repeat_interleave(2)
tensor([0.2258, 0.2258, 0.2024, 0.2024, 0.7398, 0.7398, 0.3576, 0.3576, 0.3801,
        0.3801, 0.3540, 0.3540])
t2.repeat_interleave(2,dim=0)
tensor([[0.2258, 0.2024],
        [0.2258, 0.2024],
        [0.7398, 0.3576],
        [0.7398, 0.3576],
        [0.3801, 0.3540],
        [0.3801, 0.3540]])
t2.repeat_interleave(2,dim=1)
tensor([[0.2258, 0.2258, 0.2024, 0.2024],
        [0.7398, 0.7398, 0.3576, 0.3576],
        [0.3801, 0.3801, 0.3540, 0.3540]])
t2.repeat_interleave(torch.tensor([1,2,3]),dim=0)
tensor([[0.2258, 0.2024],
        [0.7398, 0.3576],
        [0.7398, 0.3576],
        [0.3801, 0.3540],
        [0.3801, 0.3540],
        [0.3801, 0.3540]])


### Padding

In [49]:
# Tensor Padding
from torch.nn import functional as F

x = torch.tensor([[1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4]])

pad_left   = 1
pad_right  = 2
pad_top    = 1
pad_bottom = 2

a = F.pad( x, (pad_left,pad_right,pad_top,pad_bottom), mode = 'constant' )

print(a)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])


### Casting

In [54]:
t = torch.tensor([True,False])
t.type(torch.int)

tensor([1, 0], dtype=torch.int32)

## Inplace and Empty tensor

In [4]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [5]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.9782, 1.4988, 1.6624],
        [0.7805, 0.6465, 0.5244],
        [1.2240, 1.1926, 0.8954],
        [1.0103, 0.6106, 0.7199],
        [1.5926, 1.0187, 0.8834]])


In [6]:
# adds x to y
y.add_(x)
print(y)


tensor([[0.9782, 1.4988, 1.6624],
        [0.7805, 0.6465, 0.5244],
        [1.2240, 1.1926, 0.8954],
        [1.0103, 0.6106, 0.7199],
        [1.5926, 1.0187, 0.8834]])


### MathOperation


In [55]:
# Point-wise/element-wise operations
# Similar to numpy arrays, torch offers all the basic mathematical operations and is extremely convenient
# Below we list some of the most commonly used operations

t1 = torch.rand(3)
t2 = torch.rand(3)
t3 = torch.rand(size=(3,4))
t4 = torch.rand(size=(3,4))
t5 = torch.rand(size=(3,1))

print('original t1:')
print(t1)

print('original t2:')
print(t2)

print('original t3:')
print(t3)

print('original t4:')
print(t4)

print('original t5:')
print(t5)

# Addition with scalar
print('t1+10')
print(t1+10)

# Addition
print('t1+t2')
print(t1+t2)

# Multiplication with scalar
print('t1*-10')
print(t1*-10)

# Elementwise multiplication
print('t1*t2')
print(t1*t2)

# Absolute value
print('abs(-10*t1)')
print(abs(-10*t1))

# Similar operations extend to multi-dimensional tensors
print('t3+t4')
print(t3+t4)

# Broadcasting b/w arrays of different dimensions
# Note; When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the tensor should have length 1 in that specific dimension
print(t3+t5)

original t1:
tensor([0.0996, 0.5039, 0.5145])
original t2:
tensor([0.2802, 0.8284, 0.3067])
original t3:
tensor([[0.2086, 0.1127, 0.9981, 0.0853],
        [0.8224, 0.1656, 0.5069, 0.4191],
        [0.2454, 0.8722, 0.9818, 0.7027]])
original t4:
tensor([[0.9023, 0.2309, 0.4151, 0.7825],
        [0.1093, 0.2912, 0.4206, 0.6876],
        [0.7031, 0.8184, 0.4413, 0.8967]])
original t5:
tensor([[0.1108],
        [0.3183],
        [0.2156]])
t1+10
tensor([10.0996, 10.5039, 10.5145])
t1+t2
tensor([0.3798, 1.3323, 0.8212])
t1*-10
tensor([-0.9962, -5.0392, -5.1451])
t1*t2
tensor([0.0279, 0.4174, 0.1578])
abs(-10*t1)
tensor([0.9962, 5.0392, 5.1451])
t3+t4
tensor([[1.1109, 0.3435, 1.4132, 0.8677],
        [0.9317, 0.4568, 0.9275, 1.1067],
        [0.9485, 1.6906, 1.4231, 1.5994]])
tensor([[0.3194, 0.2235, 1.1090, 0.1961],
        [1.1407, 0.4838, 0.8252, 0.7374],
        [0.4610, 1.0877, 1.1974, 0.9182]])


### Reduction

In [56]:
# Reduction Operations
# Torch supports all commonly used mathematical reduction operations such as sum(), mean(), std(), max(), argmax(), prod(), unique() etc.
# These can either be applied on the entire tensor or along specific dimensions.

t1 = torch.rand(3)
t2 = torch.rand(size=(3,4))

print('original t1:')
print(t1)

print('original t2:')
print(t2)

print('t1.sum()')
print(t1.sum())

print('t2.sum()')
print(t2.sum())

print('t2.sum(axis=0)')
print(t2.sum(axis=0))

print('t2.sum(axis=1)')
print(t2.sum(axis=1))

original t1:
tensor([0.2349, 0.3288, 0.5180])
original t2:
tensor([[0.8625, 0.0368, 0.2810, 0.0829],
        [0.5923, 0.8180, 0.7160, 0.8264],
        [0.0045, 0.1453, 0.2816, 0.6819]])
t1.sum()
tensor(1.0816)
t2.sum()
tensor(5.3292)
t2.sum(axis=0)
tensor([1.4594, 1.0001, 1.2786, 1.5912])
t2.sum(axis=1)
tensor([1.2632, 2.9527, 1.1134])


### any,all and boolean

In [57]:
# Comparison Operations

t1 = torch.rand(size=(3,4))
t2 = torch.rand(size=(3,4))
t3 = torch.rand(size=(3,4))

print('original t1:')
print(t1)

print('original t2:')
print(t2)

print('original t3:')
print(t3)

# Basic comparison operations
print('t1>t3')
print(t1>t2)

print('t2!=t3')
print(t2!=t3)

# Combining reduction operations with boolean tensors
print((t1>t2).any())
print((t1>t2).all())
print((t1>t2).any(axis=0))
print((t1>t2).any(axis=1))

print((t2!=t3).any())
print((t2!=t3).all())

original t1:
tensor([[0.4313, 0.5304, 0.2393, 0.4932],
        [0.5680, 0.3317, 0.2545, 0.3140],
        [0.9841, 0.1412, 0.6072, 0.1300]])
original t2:
tensor([[0.6543, 0.7535, 0.1301, 0.5513],
        [0.1023, 0.5796, 0.9846, 0.9082],
        [0.1966, 0.0105, 0.8014, 0.3972]])
original t3:
tensor([[0.4616, 0.7314, 0.5932, 0.6725],
        [0.9817, 0.3001, 0.0679, 0.8995],
        [0.8529, 0.2771, 0.6490, 0.4475]])
t1>t3
tensor([[False, False,  True, False],
        [ True, False, False, False],
        [ True,  True, False, False]])
t2!=t3
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor(True)
tensor(False)
tensor([ True,  True,  True, False])
tensor([True, True, True])
tensor(True)
tensor(True)


In [59]:
# Vector/Matrix operations
# Torch offers all baisc matrix and vector operations. Moreover there are some helpful utilities which are specific to how data in DL is organized.

# vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

# matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

# batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)

print('tensor1')
print(tensor1)
print('tensor2')
print(tensor2)

print('torch.matmul(tensor1, tensor2)')
print(torch.matmul(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2).size())

tensor1
tensor([ 1.3672,  1.0618, -1.7354])
tensor2
tensor([-0.9224,  0.5498,  0.7124])
torch.matmul(tensor1, tensor2)
tensor(-1.9136)
torch.Size([])
tensor1
tensor([[ 1.1456, -0.0869, -2.2937,  0.0287],
        [ 0.6608,  0.2981,  1.0267, -1.5865],
        [ 2.6014,  1.1211,  0.1026, -0.8408]])
tensor2
tensor([-1.1190, -0.3401, -0.4586, -0.6154])
torch.matmul(tensor1, tensor2)
tensor([-0.2182, -0.3352, -2.8217])
torch.Size([3])
tensor1
tensor([[[-0.0075, -0.7547,  0.1789,  1.7582],
         [ 1.1619, -0.1546, -1.3757, -0.2298],
         [-0.1599, -0.8660,  0.3677,  2.0602]],

        [[-0.0768,  1.8757, -1.2249,  1.2775],
         [ 0.8758,  0.5901,  0.4997,  0.8469],
         [ 1.0623, -0.2962,  0.3615,  0.0172]],

        [[-0.3895,  0.5070,  0.5560,  0.8798],
         [ 1.6900,  0.7874,  0.3618,  0.0669],
         [-1.8549,  0.8328,  0.0971,  1.1864]],

        [[ 0.2424,  0.4802,  1.6255, -0.1596],
         [-1.3538, -1.3770,  1.0416,  0.6482],
         [ 0.1232, -0.6626,  0.0557,