## Numpy Refrences


#### Install Numpy

In [2]:
#pip install numpy

#### Import Numpy

In [2]:
import numpy as np

### Contents
#### 1. Initialize Numpy arrays
#### 2.  Changing nparrays without changing its elements

---
<br />

### *1) Initialize Numpy arrays*

In [3]:
 # Initialize Directly
arr1 = np.array([1,2,3])
print(f'Initialize Directly: {arr1}')

#Check Type of a data structure
print(f'\nType of arr1: {type(arr1)}\n')


# Initalize through a variable
a_list = [1,2,4,5]
arr2 = np.array(a_list) 
print(f'Initalize through a variable: {arr2}')


# arr_3 is mutable
a_list2 = (1,2,3,4)
arr_3 = np.array(a_list2)
print(f'Last array: {arr_3}')

#Initialize nparray with data type
print(f'Initialize nparray with data type: {np.array([1,2,3],dtype=float)}') 

#Initialize nparray as float
print(f'Initialize nparray with Same type: {np.array([1.,2,3])}') 


#Initialize Matrix
np.array(np.mat('1 2; 3 4'))


Initialize Directly: [1 2 3]

Type of arr1: <class 'numpy.ndarray'>

Initalize through a variable: [1 2 4 5]
Last array: [1 2 3 4]
Initialize nparray with data type: [1. 2. 3.]
Initialize nparray with Same type: [1. 2. 3.]


array([[1, 2],
       [3, 4]])

Numpy doc to Generate Numbers from Different Distribution: https://numpy.org/doc/stable/reference/random/generator.html

In [4]:
# Initialize a zeros nparray 
print(f'Initialize Zeros: \n{np.zeros((2,3))}\n') # Note the argument is shape so double brackets

# Initialize a Ones nparray 
print(f'Initialize Ones: \n{np.ones((2,3),dtype=int)}\n') # Note the argument is shape so double brackets

# Random int with range 2-10 and size (2,3)
print(f'Random int with range 2-10 and size (2,3):\n {np.random.randint(2,10,size=(2,3))}\n') 


# Standard Normally distributed N(0,1) numbers of size (2,4,5)
print(f' Standard Normally distributed N(0,1) numbers of size (2,4,5):\n {np.random.randn(2,4,5)}')# Note no size as argument

Initialize Zeros: 
[[0. 0. 0.]
 [0. 0. 0.]]

Initialize Ones: 
[[1 1 1]
 [1 1 1]]

Random int with range 2-10 and size (2,3):
 [[5 7 4]
 [8 5 5]]

 Standard Normally distributed N(0,1) numbers of size (2,4,5):
 [[[-1.16456204 -0.62762457  1.56695697  0.63058526  0.0913998 ]
  [ 0.22115096 -0.7210442   0.44597131  3.45179773 -1.37218112]
  [ 1.37732659  1.00639442  0.21885697  1.04458115  0.16579038]
  [-0.37064219 -1.41779211 -0.85772923  0.26981747 -0.13578791]]

 [[ 0.0627123  -1.79149639 -0.26605725 -0.92296566  1.3699916 ]
  [ 0.52720234  1.43909736  0.24463286 -1.59903704 -0.13599803]
  [-0.05443366  0.56270225  0.84681682  0.62646489  1.07871443]
  [ 0.3039596   0.65468994  0.02241101 -1.67634156 -0.1903996 ]]]


In [5]:
# Arrange a numpy array
print(f'Arrange: {np.arange(3,10)}')

#  evenly spaced numbers over a specified interval
print(f'LineSpace: {np.linspace(2.0, 3.0, num=5)}')

Arrange: [3 4 5 6 7 8 9]
LineSpace: [2.   2.25 2.5  2.75 3.  ]


 #### 2) *Changing nparrays without changing its elements*

In [6]:
#Reshape the nparray
arr_a = np.arange(12)
print(f'arr_a before: {arr_a}')

arr_b = np.reshape(arr_a,(3,4))
print(f'Reshape the dimension of nparray:\n {arr_b}\n') # Note : dimension should match

#Shuffling the nparray
np.random.shuffle(arr_a)
print(f'Shuffling arr_a: {arr_a}')

# Permutation of nparray
arr = np.arange(9).reshape((3, 3))
np.random.permutation(arr)

arr_a before: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape the dimension of nparray:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Shuffling arr_a: [ 2  1  8  7  3  6  0  5  9  4 11 10]


array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [7]:
# Transpose
# Flatten
# squeeze / unsqueeze
#